param vmName string
param location string
param serverName string = 'AzValheim Test'
param worldName string = 'AzValheim'
param serverPassword string {
  secure: true
  default: 'changethispassword'
}

var vmScriptTemplate = 'IyEvYmluL2Jhc2gKYXB0IHVwZGF0ZSAteQphcHQgdXBncmFkZSAteQoKZWNobyBzdGVhbWNtZCBzdGVhbS9saWNlbnNlIG5vdGUgJycgfCBkZWJjb25mLXNldC1zZWxlY3Rpb25zCmVjaG8gc3RlYW1jbWQgc3RlYW0vcXVlc3Rpb24gc2VsZWN0ICdJIEFHUkVFJyB8IGRlYmNvbmYtc2V0LXNlbGVjdGlvbnMKCmFkZC1hcHQtcmVwb3NpdG9yeSAteSBtdWx0aXZlcnNlCmRwa2cgLS1hZGQtYXJjaGl0ZWN0dXJlIGkzODYKYXB0IHVwZGF0ZSAteQphcHQgaW5zdGFsbCBzdGVhbWNtZCBsaWJzZGwyLTIuMC0wIGxpYnNkbDItMi4wLTA6aTM4NiAgLXkKCnVzcj0iU3RlYW0iCmhvbWU9Ii9ob21lLyR1c3IiCnN0ZWFtY21kPSIkaG9tZS9zdGVhbWNtZCIKdmFsZGlyPSIkaG9tZS92YWxoZWltIgp2YWxkYXRhPSIkdmFsZGlyL2RhdGEiCnZhbHNlcnZlcj0iJHZhbGRpci9zZXJ2ZXIiCnZhbHN0YXJ0PSIkdmFsZGlyL3N0YXJ0LnNoIgoKdXNlcmFkZCAtLWNyZWF0ZS1ob21lIC0tc2hlbGwgL2Jpbi9iYXNoIC0tc3lzdGVtICR1c3IKbG4gLXMgL3Vzci9nYW1lcy9zdGVhbWNtZCAkc3RlYW1jbWQKCm1rZGlyICR2YWxkaXIKbWtkaXIgJHZhbGRhdGEKbWtkaXIgJHZhbHNlcnZlcgoKY2F0ID4gJHZhbHN0YXJ0IDw8RU9GCiMhL2Jpbi9iYXNoCmV4cG9ydCB0ZW1wbGRwYXRoPVwkTERfTElCUkFSWV9QQVRICmV4cG9ydCBMRF9MSUJSQVJZX1BBVEg9Li9saW51eDY0OlwkTERfTElCUkFSWV9QQVRICmV4cG9ydCBTdGVhbUFwcElkPTg5Mjk3MAokdmFsc2VydmVyL3ZhbGhlaW1fc2VydmVyLng4Nl82NCAtbmFtZSAie1NlcnZlck5hbWV9IiAtcG9ydCAyNDU2IC1ub2dyYXBoaWNzIC1iYXRjaG1vZGUgLXdvcmxkICJ7V29ybGROYW1lfSIgLXNhdmVkaXIgIiR2YWxkYXRhIiAtcGFzc3dvcmQgIntTZXJ2ZXJQYXNzd29yZH0iIApleHBvcnQgTERfTElCUkFSWV9QQVRIPVwkdGVtcGxkcGF0aApFT0YKCmNobW9kICt4ICR2YWxzdGFydAoKY2F0ID4gL2V0Yy9zeXN0ZW1kL3N5c3RlbS92YWxoZWltLnNlcnZpY2UgPDxFT0YKW1VuaXRdCkRlc2NyaXB0aW9uPVZhbGhlaW0gU2VydmVyCldhbnRzPW5ldHdvcmstb25saW5lLnRhcmdldApBZnRlcj1zeXNsb2cudGFyZ2V0IG5ldHdvcmsudGFyZ2V0IG5zcy1sb29rdXAudGFyZ2V0IG5ldHdvcmstb25saW5lLnRhcmdldAoKW1NlcnZpY2VdClR5cGU9c2ltcGxlClJlc3RhcnQ9b24tZmFpbHVyZQpSZXN0YXJ0U2VjPTIwClRpbWVvdXRTZWM9NjAwClN0YXJ0TGltaXRCdXJzdD0zClVzZXI9JHVzcgpHcm91cD0kdXNyCkV4ZWNTdGFydFByZT0kc3RlYW1jbWQgK2xvZ2luIGFub255bW91cyArZm9yY2VfaW5zdGFsbF9kaXIgJHZhbHNlcnZlciArYXBwX3VwZGF0ZSA4OTY2NjAgdmFsaWRhdGUgK2V4aXQKRXhlY1N0YXJ0PSR2YWxzdGFydApFeGVjUmVsb2FkPS9iaW4va2lsbCAtcyBIVVAgJE1BSU5QSUQKS2lsbFNpZ25hbD1TSUdJTlQKV29ya2luZ0RpcmVjdG9yeT0kdmFsc2VydmVyCkxpbWl0Tk9GSUxFPTEwMDAwMAoKW0luc3RhbGxdCldhbnRlZEJ5PW11bHRpLXVzZXIudGFyZ2V0CkVPRgoKY2hvd24gLVJmICIkdXNyOiR1c3IiICIkaG9tZSIKCnN5c3RlbWN0bCBkYWVtb24tcmVsb2FkCnN5c3RlbWN0bCBlbmFibGUgdmFsaGVpbQpzeXN0ZW1jdGwgc3RhcnQgdmFsaGVpbSAtLW5vLWJsb2Nr'
var vmScriptServerNameTemplate = '{ServerName}'
var vmScriptWorldNameTemplate = '{WorldName}'
var vmScriptServerPasswordTemplate = '{ServerPassword}'
var vmScript = base64(replace(replace(replace(base64ToString(vmScriptTemplate), vmScriptServerNameTemplate, serverName), vmScriptWorldNameTemplate, worldName), vmScriptServerPasswordTemplate, serverPassword))

resource valheimCustomScript 'Microsoft.Compute/virtualMachines/extensions@2019-03-01' = {
  name: '${vmName}/ValheimSetup'
  location: location
  properties: {
    publisher: 'Microsoft.Azure.Extensions'
    type: 'CustomScript'
    typeHandlerVersion: '2.0'
    autoUpgradeMinorVersion: true
    settings: {
      script: vmScript
    }
  }
}